import type {
  PcBuilderCategory,
  PcBuilderComponent,
} from "./types";

/**
 * Fictional NODRIA demo fixtures. Specifications and prices are illustrative;
 * they are not sourced from an actual product catalogue.
 */
export const pcBuilderComponents = [
  {
    id: "cpu-vector-7-9700",
    category: "cpu",
    name: "Vector 7 9700",
    manufacturer: "NODRIA",
    priceEur: 369,
    description: "Procesador de 8 núcleos para equipos de uso general y gaming.",
    socket: "AM5",
    memoryGenerations: ["DDR5"],
    estimatedPowerW: 120,
    integratedGraphics: true,
  },
  {
    id: "cpu-coreforge-9-285",
    category: "cpu",
    name: "CoreForge 9 285",
    manufacturer: "NODRIA",
    priceEur: 579,
    description: "Procesador de 16 núcleos para creación y cargas de trabajo exigentes.",
    socket: "LGA1851",
    memoryGenerations: ["DDR5"],
    estimatedPowerW: 180,
    integratedGraphics: true,
  },
  {
    id: "cpu-pulse-5-7600",
    category: "cpu",
    name: "Pulse 5 7600",
    manufacturer: "NODRIA",
    priceEur: 219,
    description: "Procesador de 6 núcleos pensado para una configuración equilibrada.",
    socket: "LGA1700",
    memoryGenerations: ["DDR4"],
    estimatedPowerW: 75,
    integratedGraphics: false,
  },
  {
    id: "mb-aurora-b850",
    category: "motherboard",
    name: "Aurora B850 WiFi",
    manufacturer: "NODRIA",
    priceEur: 229,
    description: "Placa ATX con conectividad Wi-Fi integrada.",
    socket: "AM5",
    formFactor: "ATX",
    memoryGeneration: "DDR5",
    maxMemoryGb: 192,
    estimatedPowerW: 50,
  },
  {
    id: "mb-atelier-z890",
    category: "motherboard",
    name: "Atelier Z890 Creator",
    manufacturer: "NODRIA",
    priceEur: 349,
    description: "Placa ATX con conexiones ampliadas para creación de contenido.",
    socket: "LGA1851",
    formFactor: "ATX",
    memoryGeneration: "DDR5",
    maxMemoryGb: 192,
    estimatedPowerW: 50,
  },
  {
    id: "mb-pulse-b760-d4",
    category: "motherboard",
    name: "Pulse B760 D4",
    manufacturer: "NODRIA",
    priceEur: 159,
    description: "Placa microATX compatible con memoria DDR4.",
    socket: "LGA1700",
    formFactor: "microATX",
    memoryGeneration: "DDR4",
    maxMemoryGb: 128,
    estimatedPowerW: 50,
  },
  {
    id: "ram-lumen-32-ddr5",
    category: "memory",
    name: "Lumen 32 GB DDR5 6000",
    manufacturer: "NODRIA",
    priceEur: 139,
    description: "Kit de 2 módulos para equipos DDR5.",
    generation: "DDR5",
    capacityGb: 32,
    kitModules: 2,
    speedMtPerS: 6000,
    estimatedPowerW: 10,
  },
  {
    id: "ram-lumen-32-ddr4",
    category: "memory",
    name: "Lumen 32 GB DDR4 3600",
    manufacturer: "NODRIA",
    priceEur: 89,
    description: "Kit de 2 módulos para equipos DDR4.",
    generation: "DDR4",
    capacityGb: 32,
    kitModules: 2,
    speedMtPerS: 3600,
    estimatedPowerW: 8,
  },
  {
    id: "case-prism-atx",
    category: "case",
    name: "Prism Air ATX",
    manufacturer: "NODRIA",
    priceEur: 129,
    description: "Torre ATX con frontal ventilado y espacio amplio para gráfica.",
    supportedFormFactors: ["E-ATX", "ATX", "microATX", "Mini-ITX"],
    maxGpuLengthMm: 400,
    estimatedPowerW: 25,
  },
  {
    id: "case-arc-micro",
    category: "case",
    name: "Arc Compact",
    manufacturer: "NODRIA",
    priceEur: 99,
    description: "Torre compacta compatible con placas microATX y Mini-ITX.",
    supportedFormFactors: ["microATX", "Mini-ITX"],
    maxGpuLengthMm: 320,
    estimatedPowerW: 25,
  },
  {
    id: "gpu-pulse-770",
    category: "gpu",
    name: "Pulse 770 12 GB",
    manufacturer: "NODRIA",
    priceEur: 599,
    description: "Gráfica de 12 GB para gaming y aplicaciones creativas.",
    lengthMm: 304,
    estimatedPowerW: 220,
  },
  {
    id: "gpu-forge-890",
    category: "gpu",
    name: "Forge 890 16 GB",
    manufacturer: "NODRIA",
    priceEur: 899,
    description: "Gráfica de alto rendimiento con refrigeración de triple ventilador.",
    lengthMm: 358,
    estimatedPowerW: 360,
  },
  {
    id: "psu-lumen-650",
    category: "psu",
    name: "Lumen 650 Gold",
    manufacturer: "NODRIA",
    priceEur: 99,
    description: "Fuente modular de 650 W con certificación 80+ Gold.",
    capacityW: 650,
    efficiencyLabel: "80+ Gold",
  },
  {
    id: "psu-lumen-750",
    category: "psu",
    name: "Lumen 750 Gold",
    manufacturer: "NODRIA",
    priceEur: 119,
    description: "Fuente modular de 750 W con certificación 80+ Gold.",
    capacityW: 750,
    efficiencyLabel: "80+ Gold",
  },
  {
    id: "psu-forge-850",
    category: "psu",
    name: "Forge 850 Platinum",
    manufacturer: "NODRIA",
    priceEur: 169,
    description: "Fuente modular de 850 W con certificación 80+ Platinum.",
    capacityW: 850,
    efficiencyLabel: "80+ Platinum",
  },
  {
    id: "storage-arc-2tb",
    category: "storage",
    name: "Arc NVMe 2 TB",
    manufacturer: "NODRIA",
    priceEur: 159,
    description: "SSD NVMe PCIe 4.0 para sistema, aplicaciones y biblioteca de juegos.",
    capacityTb: 2,
    interface: "NVMe PCIe 4.0",
    estimatedPowerW: 7,
  },
  {
    id: "storage-arc-1tb-gen5",
    category: "storage",
    name: "Arc NVMe 1 TB Gen 5",
    manufacturer: "NODRIA",
    priceEur: 149,
    description: "SSD NVMe PCIe 5.0 compacto para cargas con transferencias intensivas.",
    capacityTb: 1,
    interface: "NVMe PCIe 5.0",
    estimatedPowerW: 10,
  },
  {
    id: "cooler-boreal-240",
    category: "cooler",
    name: "Boreal Liquid 240",
    manufacturer: "NODRIA",
    priceEur: 119,
    description: "Refrigeración líquida de circuito cerrado con radiador de 240 mm.",
    supportedSockets: ["AM5", "LGA1851", "LGA1700"],
    estimatedPowerW: 12,
  },
] as const satisfies readonly PcBuilderComponent[];

export const requiredPcBuilderCategories = [
  "cpu",
  "motherboard",
  "memory",
  "case",
  "psu",
] as const satisfies readonly PcBuilderCategory[];

export const optionalPcBuilderCategories = [
  "gpu",
  "storage",
  "cooler",
] as const satisfies readonly PcBuilderCategory[];
