import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { buildDataset } from './dataset.mjs';
import { validateDataset } from './validate.mjs';

const repo = new URL('../../', import.meta.url);
function renderMigrationSql(data, generatorPath) {
  return `-- Generated by node ${generatorPath}; edit dataset.mjs, then regenerate.
-- Fictional, additive catalogue only. Never run the development seed remotely.
-- No schema/grant/RLS changes, costs, buyers, reviews or historical snapshots.
do $catalog_depth$
declare
  data jsonb := $dataset$${JSON.stringify(data, null, 2)}$dataset$::jsonb;
  c jsonb;
  p jsonb;
  s jsonb;
  v_parent_id uuid;
  root_id uuid;
  leaf_id uuid;
  warehouse_id uuid;
  inserted_id text;
begin
  -- Serialize this dataset's reruns; normal unique constraints still protect
  -- competing operational inserts. Every exception rolls back this whole block.
  perform pg_advisory_xact_lock(hashtextextended('nodria-depth-v1', 0));
  if exists (
    select 1 from jsonb_array_elements(data->'products') d
    join public.products existing on existing.id = d->>'id'
      or existing.sku = d->>'sku' or existing.slug = d->>'slug'
    where existing.id <> d->>'id' or existing.sku <> d->>'sku' or existing.slug <> d->>'slug'
  ) then
    raise exception 'Catalogue identity collision: inspect ID/SKU/slug; nothing overwritten';
  end if;
  if exists (
    select 1 from jsonb_array_elements(data->'products') d
    join public.product_variants v on v.sku = d->'variant'->>'sku' or v.id = (d->'variant'->>'id')::uuid
    where v.product_id <> d->>'id' or v.id <> (d->'variant'->>'id')::uuid or v.sku <> d->'variant'->>'sku'
  ) then
    raise exception 'Variant identity collision: nothing overwritten';
  end if;

  -- Roots precede leaves. Existing category IDs and their content are preserved.
  for c in select value from jsonb_array_elements(data->'categories') loop
    v_parent_id := null;
    if c->>'parent_slug' is not null then
      select id into strict v_parent_id from public.categories where slug = c->>'parent_slug' and is_active;
    end if;
    insert into public.categories (id, slug, name, description, parent_id, sort_order, is_active)
    values ((c->>'id')::uuid, c->>'slug', c->>'name', c->>'description', v_parent_id, (c->>'sort_order')::integer, true)
    on conflict (slug) do nothing;
    if not exists (select 1 from public.categories cat where cat.slug = c->>'slug' and cat.is_active and cat.parent_id is not distinct from v_parent_id) then
      raise exception 'Inactive category or hierarchy collision: %', c->>'slug';
    end if;
  end loop;

  insert into public.warehouses (code, name, city, country_code, is_active)
  values ('MAD-CENTRAL', 'NODRIA Centro logístico Madrid', 'Madrid', 'ES', true)
  on conflict (code) do nothing;
  select id into strict warehouse_id from public.warehouses where code = 'MAD-CENTRAL' and is_active;

  for p in select value from jsonb_array_elements(data->'products') loop
    inserted_id := null;
    insert into public.products (id, slug, sku, name, brand, summary, description, image_url, image_alt, badge,
      rating_average, rating_count, is_featured, is_published, published_at)
    values (p->>'id', p->>'slug', p->>'sku', p->>'name', p->>'brand', p->>'summary', p->>'description', p->>'image_url', p->>'image_alt', p->>'badge',
      (p->>'rating_average')::numeric, (p->>'rating_count')::integer, (p->>'is_featured')::boolean, true, (data->>'published_at')::timestamptz)
    on conflict do nothing returning id into inserted_id;

    -- Do not heal/reprice/replenish existing products, even this fixture's own
    -- products after an operator has modified them. Only new inserts get children.
    if inserted_id is not null then
      select id into strict root_id from public.categories where slug = p->>'root_category';
      select id into strict leaf_id from public.categories where slug = p->>'category_slug';
      insert into public.product_categories (product_id, category_id) values (inserted_id, root_id), (inserted_id, leaf_id);
      insert into public.product_variants (id, product_id, sku, title, attributes, current_price, compare_at_price, currency, tax_rate, is_active)
      values ((p->'variant'->>'id')::uuid, inserted_id, p->'variant'->>'sku', p->'variant'->>'title', p->'variant'->'attributes',
        (p->'variant'->>'current_price')::numeric, (p->'variant'->>'compare_at_price')::numeric, p->'variant'->>'currency', (p->'variant'->>'tax_rate')::numeric, true);
      for s in select value from jsonb_array_elements(p->'specifications') loop
        insert into public.product_specifications (product_id, label, value, sort_order)
        values (inserted_id, s->>'label', s->>'value', (s->>'sort_order')::integer);
      end loop;
      insert into public.inventory (warehouse_id, variant_id, on_hand, reserved)
      values (warehouse_id, (p->'variant'->>'id')::uuid, (p->>'stock')::integer, 0);
      if (p->>'stock')::integer > 0 then
        insert into public.inventory_movements (warehouse_id, variant_id, movement_type, quantity_delta, on_hand_after, reason)
        values (warehouse_id, (p->'variant'->>'id')::uuid, 'receipt', (p->>'stock')::integer, (p->>'stock')::integer, 'Inventario inicial sintético nodria-depth-v1; no es una recepción comercial.');
      end if;
    end if;
  end loop;
end;
$catalog_depth$;
`;
}

export function renderMigration(data) {
  validateDataset(data);
  return renderMigrationSql(data, 'scripts/catalog/generate.mjs');
}

export function renderPcBuilderExpansionMigration(data) {
  validateDataset(data);
  const categories = new Set(Object.values({
    procesadores: 'cpu', 'placas-base': 'motherboard', 'memoria-ram': 'memory',
    cajas: 'case', 'fuentes-alimentacion': 'psu', 'tarjetas-graficas': 'gpu',
    refrigeracion: 'cooler', 'ssd-internos': 'storage',
  }));
  const additions = data.products.filter(product =>
    product.variant.attributes.pc_builder && /-(05|06|07|08)$/.test(product.sku),
  );
  const counts = new Map([...categories].map(category => [category, 0]));
  for (const product of additions) {
    const category = product.variant.attributes.pc_builder.category;
    if (!counts.has(category)) throw new Error(`Unexpected PC Builder category: ${category}`);
    counts.set(category, counts.get(category) + 1);
  }
  if (additions.length !== 32 || [...counts.values()].some(count => count !== 4)) {
    throw new Error('Expected exactly four new PC Builder editions for each of eight component categories');
  }
  return renderMigrationSql({ ...data, products: additions }, 'scripts/catalog/generate-pc-builder-expansion.mjs');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const migrations = readdirSync(new URL('supabase/migrations/', repo)).filter(name => name.endsWith('_catalog_depth_dataset.sql'));
  if (migrations.length !== 1) throw new Error('Create exactly one migration with supabase migration new catalog_depth_dataset');
  const path = new URL(`supabase/migrations/${migrations[0]}`, repo);
  const data = buildDataset();
  const generated = renderMigration(data);
  if (process.argv.includes('--check')) {
    if (readFileSync(path, 'utf8').replaceAll('\r\n', '\n') !== generated) throw new Error('Migration differs from deterministic source; regenerate');
  } else writeFileSync(path, generated, 'utf8');
  console.log({ ...validateDataset(data), migration: migrations[0], checked: process.argv.includes('--check') });
}
