import { randomUUID } from "node:crypto";
import { beforeEach, describe, expect, it, vi } from "vitest";

const procurementMock = vi.hoisted(() => ({ getAccess: vi.fn() }));
vi.mock("@/lib/inventory/procurement/access", () => ({ getProcurementAccess: procurementMock.getAccess }));

type RouteModule = typeof import("@/app/api/backoffice/procurement/purchase-orders/route");
let purchaseOrderRoute: RouteModule;
let supplierRoute: typeof import("@/app/api/backoffice/procurement/suppliers/route");
let receiptRoute: typeof import("@/app/api/backoffice/procurement/purchase-orders/[purchaseOrderId]/receipts/route");
const supplierId = "20000000-0000-4000-8000-000000000101";
const warehouseId = "20000000-0000-4000-8000-000000000102";
const variantId = "20000000-0000-4000-8000-000000000103";

function request(url: string, body: unknown, origin = "http://localhost") {
  return new Request(`http://localhost${url}`, {
    method: "POST", headers: { "content-type": "application/json", origin, host: "localhost" }, body: JSON.stringify(body),
  });
}

function readyAccess(rpc = vi.fn()) {
  procurementMock.getAccess.mockResolvedValueOnce({ status: "ready", supabase: { rpc } });
  return rpc;
}

beforeEach(async () => {
  procurementMock.getAccess.mockReset();
  purchaseOrderRoute = await import("@/app/api/backoffice/procurement/purchase-orders/route");
  supplierRoute = await import("@/app/api/backoffice/procurement/suppliers/route");
  receiptRoute = await import("@/app/api/backoffice/procurement/purchase-orders/[purchaseOrderId]/receipts/route");
});

describe("procurement API contracts", () => {
  it("denies unauthorized roles before attempting a mutation", async () => {
    procurementMock.getAccess.mockResolvedValueOnce({ status: "forbidden" });
    const response = await purchaseOrderRoute.POST(request("/api/backoffice/procurement/purchase-orders", {}));
    expect(response.status).toBe(403);
    expect(await response.json()).toMatchObject({ error: expect.stringContaining("fulfillment_manager") });
  });

  it("rejects quantities and duplicate variants before calling the database", async () => {
    const rpc = readyAccess();
    const response = await purchaseOrderRoute.POST(request("/api/backoffice/procurement/purchase-orders", {
      supplierId, warehouseId, expectedDelivery: "", notes: "",
      lines: [
        { variantId, quantity: 100001, unitCost: "42.50" },
        { variantId, quantity: 1, unitCost: "4.00" },
      ],
    }));
    expect(response.status).toBe(400);
    expect(rpc).not.toHaveBeenCalled();
  });

  it("persists a supplier through the authorized RPC and validates its result", async () => {
    const rpc = readyAccess().mockResolvedValueOnce({ data: [{
      id: supplierId, supplier_code: "SUP-QA001", name: "Proveedor Demo", contact_email: null,
      contact_phone: null, notes: null, is_active: true, created_at: "2026-10-07T12:00:00.000Z",
    }], error: null });
    const response = await supplierRoute.POST(request("/api/backoffice/procurement/suppliers", {
      name: "Proveedor Demo", contactEmail: "", contactPhone: "", notes: "",
    }));
    expect(response.status).toBe(201);
    expect(await response.json()).toMatchObject({ supplier: { id: supplierId, isActive: true } });
    expect(rpc).toHaveBeenCalledWith("create_procurement_supplier", {
      p_name: "Proveedor Demo", p_contact_email: null, p_contact_phone: null, p_notes: null,
    });
  });

  it("returns the PO reference generated by PostgreSQL", async () => {
    const orderId = randomUUID();
    const rpc = readyAccess().mockResolvedValueOnce({ data: {
      success: true, purchaseOrderId: orderId, orderNumber: "PO-ABCDEF0123", status: "draft",
    }, error: null });
    const response = await purchaseOrderRoute.POST(request("/api/backoffice/procurement/purchase-orders", {
      supplierId, warehouseId, expectedDelivery: "2026-10-14", notes: "Ficticio",
      lines: [{ variantId, quantity: 2, unitCost: "42.50" }],
    }));
    expect(response.status).toBe(201);
    expect(await response.json()).toMatchObject({ purchaseOrder: { purchaseOrderId: orderId, status: "draft" } });
    expect(rpc).toHaveBeenCalledWith("create_purchase_order", expect.objectContaining({
      p_supplier_id: supplierId, p_warehouse_id: warehouseId,
      p_lines: [{ variantId, quantity: 2, unitCost: 42.5 }],
    }));
  });

  it("rejects cross-origin mutations and validates receipt attempts", async () => {
    const crossOriginRpc = readyAccess();
    const crossOrigin = await supplierRoute.POST(request("/api/backoffice/procurement/suppliers", {
      name: "Proveedor Demo", contactEmail: "", contactPhone: "", notes: "",
    }, "https://other.example"));
    expect(crossOrigin.status).toBe(403);
    expect(crossOriginRpc).not.toHaveBeenCalled();
  });

  it("returns a persisted quantity rejection from the receipt RPC", async () => {
    const purchaseOrderId = randomUUID();
    const receiptId = randomUUID();
    const lineId = randomUUID();
    const idempotencyKey = randomUUID();
    const rpc = readyAccess().mockResolvedValueOnce({ data: {
      success: false, replayed: false, receiptId, errorCode: "quantity_exceeds_pending",
    }, error: null });
    const response = await receiptRoute.POST(request(`/api/backoffice/procurement/purchase-orders/${purchaseOrderId}/receipts`, {
      supplierReference: "ALB-DEMO-01", idempotencyKey, lines: [{ lineId, quantity: 4 }],
    }), { params: Promise.resolve({ purchaseOrderId }) });
    expect(response.status).toBe(409);
    expect(await response.json()).toMatchObject({
      code: "quantity_exceeds_pending", receipt: { receiptId, success: false },
      error: expect.stringContaining("supera lo pendiente"),
    });
    expect(rpc).toHaveBeenCalledWith("receive_purchase_order", {
      p_purchase_order_id: purchaseOrderId, p_supplier_reference: "ALB-DEMO-01",
      p_idempotency_key: idempotencyKey, p_lines: [{ lineId, quantity: 4 }],
    });
  });
});
