import type { Metadata } from "next";
import { notFound } from "next/navigation";

const legalPages = {
  privacidad: { title: "Privacidad", intro: "Esta empresa y esta plataforma son ficticias y se utilizan únicamente con fines académicos.", sections: [["Datos en la demostración", "Los datos que introduzcas en el checkout o los formularios se guardan únicamente en archivos locales del entorno de desarrollo cuando el modo demo está habilitado. Usa los valores de ejemplo y no introduzcas datos personales reales."], ["Cuenta y autenticación", "La autenticación de Supabase solo estará disponible cuando el administrador del proyecto configure sus credenciales y políticas. En modo local no se crea una sesión real."], ["Contacto", "No existe un responsable de privacidad real para esta marca ficticia. Esta página es un texto demostrativo, no un aviso legal para un comercio operativo."]] },
  condiciones: { title: "Condiciones de uso", intro: "NODRIA es un proyecto de demostración. No se venden productos ni se realizan contratos de compraventa.", sections: [["Productos y precios", "Los productos, precios, disponibilidad, reseñas y descripciones son datos inventados para ilustrar una tienda de tecnología."], ["Pagos", "La pasarela es completamente ficticia. No introduzcas datos bancarios. Ningún pago se procesa ni se puede reclamar como transacción real."], ["Uso académico", "Las pantallas y flujos sirven para demostrar una arquitectura de producto. La aplicación no debe utilizarse para procesar pedidos, datos personales reales o pagos."]] },
  cookies: { title: "Cookies", intro: "La tienda demo guarda el carrito, los favoritos, el comparador y las configuraciones PC en el almacenamiento local del navegador.", sections: [["Almacenamiento local", "Las claves nodria.cart.v1, nodria.favorites.v1, nodria.compare.v1 y nodria.pc-build.v1 permiten continuar usando esas funciones en el mismo navegador. No se usan para publicidad."], ["Cookies de autenticación", "Supabase puede usar cookies esenciales de sesión cuando el proyecto se configure. En el modo demo local actual no hay sesión de usuario."], ["Preferencias", "Puedes borrar estos datos desde las herramientas del navegador. Si lo haces, la tienda vuelve a mostrar un estado vacío."]] },
} as const;

type LegalSlug = keyof typeof legalPages;
export async function generateMetadata({ params }: PageProps<"/legal/[slug]">): Promise<Metadata> { const { slug } = await params; return slug in legalPages ? { title: legalPages[slug as LegalSlug].title } : { title: "Información legal" }; }
export default async function LegalPage({ params }: PageProps<"/legal/[slug]">) { const { slug } = await params; if (!(slug in legalPages)) notFound(); const page = legalPages[slug as LegalSlug]; return <main className="page-wrap"><p className="eyebrow">INFORMACIÓN DEL PROYECTO</p><h1 className="page-title">{page.title}<span className="title-period">.</span></h1><div className="legal-content"><p className="legal-demo">{page.intro}</p>{page.sections.map(([title, copy]) => <section key={title}><h2>{title}</h2><p>{copy}</p></section>)}</div></main>; }
